[package]
name = "columnq"
version = "0.4.0"
homepage = "https://github.com/roapi/roapi"
license = "MIT"
authors = ["QP Hou <dave2008713@gmail.com>"]
edition = "2018"

[lib]
name = "columnq"
path = "src/lib.rs"

[dependencies]
datafusion = "5"
# datafusion = { git = "https://github.com/houqp/arrow-datafusion.git", rev = "4ddd2f5e7582ffe662aea27bbb74c58cd0715152" }

log = "0"
regex = "1"
lazy_static = "1"
graphql-parser = "0"
sqlparser = "0.10"
yup-oauth2 = "5"
thiserror = "1"
serde_json = "1"
serde_derive = "1"
serde = "1"
uriparse = "0"
bytes = { version = "1" }
reqwest = { version = "0.11", features = ["blocking", "json"] }

tokio = "1"
futures = "0.3"

# S3
rusoto_core = { version = "0.47" }
rusoto_s3 = { version = "0.47" }
rusoto_credential = { version = "0.47" }
rusoto_sts = { version = "0.47" }


deltalake = { git = "https://github.com/delta-io/delta-rs.git", rev = "2a0d3632f44a5ffa8cf6bf953615699547856719", features = ["s3", "datafusion-ext"] }
# deltalake = { version = "0", features = ["s3", "datafusion-ext"] }

[dev-dependencies]
anyhow = "1"
serde_yaml = "0.8"
tempdir = "0"
pretty_assertions = "*"

[features]
simd = ["datafusion/simd"]
